### ISSUE TITLE
Transactions and balance

### ISSUE THREAD

**Issue by ryansalatti** [kashishkhullar/pos-blockchain#11]
Thanks for the medium tutorial. I've been searching through this project for awhile but can't seem to find the issue. Starting the nodes results in "Recieved chain is not longer than the current chain", and sending transactions appear to go through on the console but balances are never updated, nor are new blocks created. @kashishkhullar

**Comment by kashishkhullar** [comment]
I have updated the documentation. Please refer to README.md
