### ISSUE TITLE
How to initiate the system?

### ISSUE THREAD

**Issue by istabraq-iot** [kashishkhullar/pos-blockchain#7]
please could provide more steps in details ? I didn't know what to do after running the nodes?

**Comment by istabraq-iot** [comment]
@kashishkhullar

**Comment by kashishkhullar** [comment]
Open postman and run the APIs. Transact with different accounts.

**Comment by istabraq-iot** [comment]
Thanks for answering ..  I have this error . it tells me:
```
    let exists = this.transactions.find(t => t.id === transaction.id);
TypeError: Cannot read property 'id' of undefined
```
and also the current amount is always zero and even if i put the initial balance:
`Amount: 10 exceeds the current balance: 0`

![Screenshot from 2020-05-10 11-00-33 - 1](https://user-images.githubusercontent.com/60552945/81506879-146b1080-9302-11ea-8c7f-8aef1d07e625.png)
![Screenshot from 2020-05-10 11-01-56](https://user-images.githubusercontent.com/60552945/81506880-1634d400-9302-11ea-914a-e879c15b6b7e.png)
![Screenshot from 2020-05-10 11-04-47](https://user-images.githubusercontent.com/60552945/81506881-1634d400-9302-11ea-8368-31750ab8532b.png)

**Comment by kashishkhullar** [comment]
Run the ICO and send some coins to other nodes

**Comment by kashishkhullar** [comment]
I have updated the documentation. Please refer to README.md
